const express = require('express')
const router = express.Router()
const { protect } = require('../middleware/authMiddleware')
const { registerUser, loginUser, getCredentials, updateUser, forgotPassword } = require("../controllers/authController")
router.route("/credentials").get(protect, getCredentials)
router.route("/register").post(registerUser)
router.route("/login").post(loginUser)
router.route("/update/:id").put(updateUser)
router.route("/forgot-password").put(forgotPassword)
module.exports = router